// Card
export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';
export const FETCH_DETAILS_REQUEST = 'FETCH_DETAILS_REQUEST';
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS';
export const FETCH_DETAILS_FAILURE = 'FETCH_DETAILS_FAILURE';
export const SET_CARDS = 'SET_CARDS';

// Filter
export const SET_FILTER = 'SET_FILTER';
export const SET_MULTI_FILTER = 'SET_MULTI_FILTER';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';

// Locale
export const SET_LOCALE = 'SET_LOCALE';

// Deck
export const SET_DECKMAKER_STATUS = 'SET_DECKMAKER_STATUS';
export const SET_CURRENT_DECK = 'SET_CURRENT_DECK';
export const SELECT_LEADER = 'SELECT_LEADER';
export const REMOVE_LEADER = 'REMOVE_LEADER';

export const SELECT_CARD = 'SELECT_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';
export const RESET_CARD = 'RESET_CARD';
export const RESET_DECK = 'RESET_DECK';
export const SELECT_DECK_URL = 'SELECT_DECK_URL';

export const ADD_DECK_REQUEST = 'ADD_DECK_REQUEST';
export const ADD_DECK_SUCCESS = 'ADD_DECK_SUCCESS';
export const ADD_DECK_FAILURE = 'ADD_DECK_FAILURE';

export const UPDATE_DECK_REQUEST = 'UPDATE_DECK_REQUEST';
export const UPDATE_DECK_SUCCESS = 'UPDATE_DECK_SUCCESS';
export const UPDATE_DECK_FAILURE = 'UPDATE_DECK_FAILURE';

// user
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const VERIFY_REQUEST = 'VERIFY_REQUEST';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_FAILURE = 'VERIFY_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const FETCH_DECKS_REQUEST = 'FETCH_DECKS_REQUEST';
export const FETCH_DECKS_SUCCESS = 'FETCH_DECKS_SUCCESS';
export const FETCH_DECKS_FAILURE = 'FETCH_DECKS_FAILURE';
