export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';
export const FETCH_DETAILS_REQUEST = 'FETCH_DETAILS_REQUEST';
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS';
export const FETCH_DETAILS_FAILURE = 'FETCH_DETAILS_FAILURE';
export const SET_CARDS = 'SET_CARDS';

export const SET_FILTER = 'SET_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const SET_LOCALE = 'SET_LOCALE';

export const SET_DECKMAKER_STATUS = 'SET_DECKMAKER_STATUS';

export const SELECT_LEADER = 'SELECT_LEADER';
export const REMOVE_LEADER = 'REMOVE_LEADER';

export const SELECT_CARD = 'SELECT_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';
